Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -35,18 +35,18 @@ steps:
 
         echo "Starting health check ............"
 
-        for i in $(seq 1 20); do
+        for i in $(seq 1 3); do
           echo "Attempt $i/20: Curling ..."
           # Use -f to fail silently on HTTP errors, -s for silent output, -o /dev/null to discard body
           #curl -f -s -o /dev/null "${_SERVICE_URL}${_HEALTH_CHECK_PATH}"
-          curl -f -s -o https://devops-challenge-ejc24ng3fa-uc.a.run.app
+          curl -f -s https://devops-challenge-ejc24ng3fa-uc.a.run.app
          
 
           if [ $? -eq 0 ]; then
             echo "Health check successful!"
             exit 0 # Success
           else
-            echo "Health check failed (exit code: $? ). Retrying in 10 seconds..."
+            echo "Health check failed (exit code: $? ). Retrying in 5 seconds..."
             sleep 10
           fi
         done
